"""property_listing_workflow

Revision ID: 05d027dac8c3
Revises: 002_admin_dashboard
Create Date: 2026-07-05 21:29:03.986665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d027dac8c3'
down_revision: Union[str, None] = '002_admin_dashboard'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_documents',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('title_deed', 'ownership_certificate', 'tax_receipt', 'identity_proof', 'noc', 'encumbrance_certificate', 'other', name='document_type_enum'), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'verified', 'rejected', name='document_status_enum'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_documents_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_documents'))
    )
    op.create_index(op.f('ix_property_documents_property_id'), 'property_documents', ['property_id'], unique=False)
    op.drop_constraint(op.f('uq_agents_email'), 'agents', type_='unique')
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=True)
    op.drop_constraint(op.f('uq_blog_posts_slug'), 'blog_posts', type_='unique')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    # Create enum types for new inquiry columns
    inquiry_type_enum = sa.Enum('inquiry', 'purchase_request', name='inquiry_type_enum')
    inquiry_type_enum.create(op.get_bind(), checkfirst=True)
    tracking_status_enum = sa.Enum('submitted', 'under_review', 'approved', 'rejected', 'completed', name='tracking_status_enum')
    tracking_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('inquiries', sa.Column('inquiry_type', inquiry_type_enum, nullable=False, server_default='inquiry'))
    op.add_column('inquiries', sa.Column('buyer_id', sa.Uuid(), nullable=True))
    op.add_column('inquiries', sa.Column('tracking_status', tracking_status_enum, nullable=False, server_default='submitted'))
    op.add_column('inquiries', sa.Column('admin_response', sa.Text(), nullable=True))
    op.create_index(op.f('ix_inquiries_buyer_id'), 'inquiries', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_inquiries_inquiry_type'), 'inquiries', ['inquiry_type'], unique=False)
    op.create_index(op.f('ix_inquiries_tracking_status'), 'inquiries', ['tracking_status'], unique=False)
    op.create_foreign_key(op.f('fk_inquiries_buyer_id_users'), 'inquiries', 'users', ['buyer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('properties', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'United States'::character varying"))
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.alter_column('property_images', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('property_images', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.alter_column('properties', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'United States'::character varying"))
    op.drop_constraint(op.f('fk_inquiries_buyer_id_users'), 'inquiries', type_='foreignkey')
    op.drop_index(op.f('ix_inquiries_tracking_status'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_inquiry_type'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_buyer_id'), table_name='inquiries')
    op.drop_column('inquiries', 'admin_response')
    op.drop_column('inquiries', 'tracking_status')
    op.drop_column('inquiries', 'buyer_id')
    op.drop_column('inquiries', 'inquiry_type')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_blog_posts_slug'), 'blog_posts', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_agents_email'), 'agents', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_property_documents_property_id'), table_name='property_documents')
    op.drop_table('property_documents')
    # ### end Alembic commands ###
