"""add_latitude_longitude

Revision ID: 72eb6af1dc88
Revises: 682cdd5795fa
Create Date: 2026-09-22 01:14:26.130384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72eb6af1dc88'
down_revision: Union[str, None] = '682cdd5795fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    op.create_index(op.f('ix_bids_created_at'), 'bids', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_created_at'), 'blog_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_tags_created_at'), 'blog_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_inquiries_created_at'), 'inquiries', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_created_at'), 'password_reset_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_property_documents_created_at'), 'property_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_features_created_at'), 'property_features', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_images_created_at'), 'property_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_property_status_history_created_at'), 'property_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_time_slots_created_at'), 'time_slots', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_time_slots_created_at'), table_name='time_slots')
    op.drop_index(op.f('ix_property_status_history_created_at'), table_name='property_status_history')
    op.drop_index(op.f('ix_property_images_created_at'), table_name='property_images')
    op.drop_index(op.f('ix_property_features_created_at'), table_name='property_features')
    op.drop_index(op.f('ix_property_documents_created_at'), table_name='property_documents')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index(op.f('ix_password_reset_tokens_created_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_inquiries_created_at'), table_name='inquiries')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_blog_tags_created_at'), table_name='blog_tags')
    op.drop_index(op.f('ix_blog_posts_created_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_bids_created_at'), table_name='bids')
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    # ### end Alembic commands ###
