"""Add clerk_id

Revision ID: 77dd6d257ab4
Revises: 006_password_reset
Create Date: 2026-08-12 01:01:50.614941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77dd6d257ab4'
down_revision: Union[str, None] = '006_password_reset'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_properties_property_code'), 'properties', type_='unique')
    op.drop_index(op.f('ix_properties_property_code'), table_name='properties')
    op.create_index(op.f('ix_properties_property_code'), 'properties', ['property_code'], unique=True)
    op.add_column('users', sa.Column('clerk_id', sa.String(length=200), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('users', 'clerk_id')
    op.drop_index(op.f('ix_properties_property_code'), table_name='properties')
    op.create_index(op.f('ix_properties_property_code'), 'properties', ['property_code'], unique=False)
    op.create_unique_constraint(op.f('uq_properties_property_code'), 'properties', ['property_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
